name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: linux
            asset_name: readme-generator-linux
          - os: windows-latest
            artifact_name: windows
            asset_name: readme-generator-windows.exe
          - os: macos-latest
            artifact_name: macos
            asset_name: readme-generator-macos

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --release
    
    - name: Run tests
      run: cargo test --verbose
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: target/release/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            linux/*
            windows/*
            macos/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
